### ISSUE TITLE
你好，想问下下载ctcdecode按照你说的发生了错误

### ISSUE THREAD

**Issue by fengchaozheng120** [yeyupiaoling/MASR#1]
出现error

**Comment by yeyupiaoling** [comment]
@fengchaozheng120 根据我的文档，不能解决吗？

**Comment by yeyupiaoling** [comment]
@fengchaozheng120 安装我文档说的，是否可以解决

由于网络问题，在安装过程中可能无法正常下载以下这两个文件，你需要自行下载这两个文件，并把它们解压到third_party目录下。

```
https://sites.google.com/site/openfst/home/openfst-down/openfst-1.6.7.tar.gz
https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
```
然后回到该源码的根目录，编辑ctcdecode/build.py，注释以下4行代码。
```
# Download/Extract openfst, boost
download_extract('https://sites.google.com/site/openfst/home/openfst-down/openfst-1.6.7.tar.gz',
                 'third_party/openfst-1.6.7.tar.gz')
download_extract('https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz',
                 'third_party/boost_1_67_0.tar.gz')
```
在ctcdecode根目录下执行以下命令开始安装ctcdecode。
```
pip install .
```

**Comment by yeyupiaoling** [comment]
问题很久没回复了，我就关闭了，需要再提问

**Comment by 33LiaoRuojie** [comment]
> @fengchaozheng120 安装我文档说的，是否可以解决
> 
> 由于网络问题，在安装过程中可能无法正常下载以下这两个文件，你需要自行下载这两个文件，并把它们解压到third_party目录下。
> 
> ```
> https://sites.google.com/site/openfst/home/openfst-down/openfst-1.6.7.tar.gz
> https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz
> ```
> 
> 然后回到该源码的根目录，编辑ctcdecode/build.py，注释以下4行代码。
> 
> ```
> # Download/Extract openfst, boost
> download_extract('https://sites.google.com/site/openfst/home/openfst-down/openfst-1.6.7.tar.gz',
>                  'third_party/openfst-1.6.7.tar.gz')
> download_extract('https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz',
>                  'third_party/boost_1_67_0.tar.gz')
> ```
> 
> 在ctcdecode根目录下执行以下命令开始安装ctcdecode。
> 
> ```
> pip install .
> ```

这两个网址似乎无法被打开，请问要如何找到这两个文件？

**Comment by yeyupiaoling** [comment]
@33LiaoRuojie 用新版本代码吧

**Comment by Lijuming33** [comment]
有用！
