### ISSUE TITLE
训练模型问题

### ISSUE THREAD

**Issue by zhaojunliing** [yeyupiaoling/MASR#14]
你好，能在百度的模型基础上，添加自己特定的语音进行训练吗

**Comment by yeyupiaoling** [comment]
@zhaojunliing 你说的百度的模型是指那个？是指这个吗：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech
这个是不行的，如果要训练，就要使用这个模型来训练。

**Comment by zhaojunliing** [comment]
下载的lm那个
对了，还有一个问题，这边在docker中安装，ctcdecode安装成功了，warp-ctc一直编译识别。
有现成的docker运行镜像吗？

**Comment by yeyupiaoling** [comment]
@zhaojunliing 没有哦，lm是语言模型，这个哪里都可以用。warp-ctc编写是要点时间的。

**Comment by zhaojunliing** [comment]
好的，那我再试一试
