### ISSUE TITLE
wer/cer 和loss 下降到多少合适

### ISSUE THREAD

**Issue by wl-junlin** [yeyupiaoling/MASR#16]
请问一下，项目带的model，在运行train.py过程中，wer/cer 是下降到了多少？还有loss？
因为nobody132的项目。cer是到了11%。

**Comment by yeyupiaoling** [comment]
@wl-junlin 太久了，我都忘记了，这个模型11%应该是很好了，想更好的模型可以看：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech

这个是最新写的：https://github.com/yeyupiaoling/PPASR

**Comment by three-sheep** [comment]
首先感谢您的贡献，为后来者提供了很多的帮助。但对于一个初学者来说，我很希望开源者能在提供源码的同时也可以提供一个预训练的权重。不一定要需要很高的准确率，但这至少可以从一定程度上解决训练资源不足的问题，节约一些时间最重要的时能够更好的理解您贡献的知识。

**Comment by yeyupiaoling** [comment]
@three-sheep 如果你能耐心看完全部文文档，那你会找到模型的下载链接。

**Comment by three-sheep** [comment]
> @three-sheep 如果你能耐心看完全部文文档，那你会找到模型的下载链接。

非常抱歉，我没有仔细阅读您的文档，以为链接是三个常用中文语音数据集下载。实在抱歉了，以小人之心度君子之腹了，您开源的代码很好，对我的学习有很多帮助。

**Comment by 827379852** [comment]
为什么我训练数据loss不收敛呢 cer错误率一直是1

**Comment by yeyupiaoling** [comment]
你的数据是多少？训练多少轮了
