### ISSUE TITLE
缺少vocabulary

### ISSUE THREAD

**Issue by jianjunwu** [yeyupiaoling/MASR#17]
刚按你提供的下载链接下载了模型，导入的时候报错，应该是缺少了vocab，能提供一份1300小时数据训练的模型的vocab嘛？

**Comment by yeyupiaoling** [comment]
@jianjunwu vocal 是在模型里面的
https://github.com/yeyupiaoling/MASR/blob/408ff4ac07b853d9e750817579dc56e009b7e2b4/infer_path.py#L39

**Comment by yeyupiaoling** [comment]
@jianjunwu 报什么错呢？
