### ISSUE TITLE
模型为何不收敛

### ISSUE THREAD

**Issue by haoyu1998** [yeyupiaoling/MASR#18]
![模型训练结果](https://user-images.githubusercontent.com/50733918/145924708-ec346e68-a20a-4702-856f-2fd92ae7a316.png)
![模型训练参数](https://user-images.githubusercontent.com/50733918/145924693-bafc8ecf-f8c7-4695-a583-760ef7ac3b72.png)
为什么Loss不收敛，且CER值为1

**Comment by yeyupiaoling** [comment]
才训练这么少，训练30个epoch再来看
