### ISSUE TITLE
报错了，debug来看，发现是ctc loss出问题了

### ISSUE THREAD

**Issue by gouqi666** [yeyupiaoling/MASR#19]
![image](https://user-images.githubusercontent.com/52353600/146186263-d514e46f-ed36-4209-adda-5b2a123d0f0c.png)

**Comment by yeyupiaoling** [comment]
是不是显存不足，你的显存是多少，如果不够的话，设计更小的batch_size

**Comment by gouqi666** [comment]
博主大大，不是显存不足啊，我都调到2了，还是不行，不知道是啥问题。全按照你的步骤来的，求解答

**Comment by gouqi666** [comment]
能不能加个联系方式，我搞了好久了。。。。

**Comment by yeyupiaoling** [comment]
你的显存是多大？

**Comment by yeyupiaoling** [comment]
Pytorch版本是多少，有没有对应上文档的版本

**Comment by gouqi666** [comment]
显存还有4G，torch版本是1.10.0，cuda版本是10.0，就这个不一样

**Comment by yeyupiaoling** [comment]
要不要你按照torch 1.6.0版本试试？4G有点少，一般都要8G以上

**Comment by gouqi666** [comment]
啊啊啊啊啊啊啊啊是torch的问题还是cuda的问题啊

**Comment by gouqi666** [comment]
我用pytorch的ctcloss能跑，但是loss是负数，天呐

**Comment by gouqi666** [comment]
博主大大有提供的现成的模型吗，我这边训练不了而且太久了...

**Comment by yeyupiaoling** [comment]
都不看文档的吗？文档最后不是有提供吗？

**Comment by yeyupiaoling** [comment]
发布了最新版本。在操场loss是用torch的，应该没有问题了
