### ISSUE TITLE
请问有人运行过吗，我想问下需要多大显卡的内存

### ISSUE THREAD

**Issue by 17702513221** [yeyupiaoling/MASR#2]
我看语言模型要2G和70G这么恐怖的吗，显卡要多大才能跑呀，速度咋样

**Comment by yeyupiaoling** [comment]
@17702513221 这些语言模型是读取在内存中的，而且可以直接在磁盘上使用，不像DeepSpeech需要全部读取到内存中。如果机器性能不够大，完全可以使用2G的语言模型。

**Comment by 17702513221** [comment]
飘零大佬给你，以前就看过你写的paddel
