### ISSUE TITLE
训练loss不收敛

### ISSUE THREAD

**Issue by 827379852** [yeyupiaoling/MASR#25]
大佬 为什么我训练自己的数聚集loss不会收敛呢 cer一直是100%
是不是跟我数聚集太少有关系呢？

**Comment by yeyupiaoling** [comment]
你的数据多少，训练多少轮了

**Comment by 827379852** [comment]
我现在数聚集只有47个 先试着训练一下  训练200轮都是不收敛

**Comment by 827379852** [comment]
![dfc42f316dbfab91f2dc9bcf9681605](https://user-images.githubusercontent.com/79695576/157620746-d42bf1bd-7925-4dcf-a879-d957c79b30d1.png)

**Comment by 827379852** [comment]
![2be9bca6eb1f4322d8c1e33c4f56869](https://user-images.githubusercontent.com/79695576/157620853-22975cda-6ccd-4506-8807-c10cc7ef6bc3.png)

**Comment by yeyupiaoling** [comment]
你是不是改了参数

**Comment by 827379852** [comment]
改了打印loss哪个频率的参数  batch改成了4
![52bac3dea6a9a5c157f6491fc8d57ba](https://user-images.githubusercontent.com/79695576/157622354-7c7a9d3a-7cef-4190-9470-c9ac7537fa23.png)

**Comment by 827379852** [comment]
最开始一直都是用的默认参数，一直不收敛，我就改了一些试试

**Comment by yeyupiaoling** [comment]
有没有用预训练模型

**Comment by 827379852** [comment]
没有使用resume_model   pretrained_model  这两个参数一直是默认值None

**Comment by yeyupiaoling** [comment]
试试，毕竟你的数据太少了

**Comment by 827379852** [comment]
好的大佬 我先试试

**Comment by 827379852** [comment]
感谢大佬 用了预训练模型确实可以了  识别结果也是对的

![5c64754c41a316324adf8e37b6b3389](https://user-images.githubusercontent.com/79695576/157627519-7cd56325-681d-4ffe-a99d-7845b1462723.png)

**Comment by yeyupiaoling** [comment]
数据是太少了
