### ISSUE TITLE
流式语音识别的功能貌似没有看到，请问现今实现了么？

### ISSUE THREAD

**Issue by RabbitBoss** [yeyupiaoling/MASR#29]

**Comment by yeyupiaoling** [comment]
模型是支持流式的，有一个小例子，在infer_path.py

**Comment by RabbitBoss** [comment]
看到了，不过我在测试新的样例时，短句时是好使的，但是切换成流式时没有输出

**Comment by yeyupiaoling** [comment]
最终也没有结果？

**Comment by RabbitBoss** [comment]
#未分段
消耗时间：1287ms, 识别结果: 今天我给我的女儿要岁钱但是我不让别人给他压岁钱而是改用压岁输, 得分: 89

#分段
------------------------------------------------
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：18ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：19ms, 识别结果: , 得分: 0
分段结果：消耗时间：22ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：14ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：14ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：18ms, 识别结果: , 得分: 0
分段结果：消耗时间：16ms, 识别结果: , 得分: 0
分段结果：消耗时间：15ms, 识别结果: , 得分: 0
分段结果：消耗时间：7ms, 识别结果: , 得分: 0
整一句结果：消耗时间：339ms, 识别结果: , 得分: 0

**Comment by yeyupiaoling** [comment]
这个不应该啊，分段最后的输出应该跟不分段输出是一样才对。
