### ISSUE TITLE
加入自己的数据训练，预测同样的数据得分却不高

### ISSUE THREAD

**Issue by bird7code** [yeyupiaoling/MASR#31]
你好，我想问一下，我加入了一点自己的数据集进去一起训练，预测的时候直接使用加入进来的数据进行测试，发现效果都不是太好，得分只有六七十的，这是数据准备出了问题吗？

**Comment by bird7code** [comment]
加入了自己的四十条语音数据和aishell数据集一起训练的

**Comment by yeyupiaoling** [comment]
首先确定两点，一、要看你的数据集是否划分到训练数据列表中，然后是使用那种解码方式，如果是贪心算法，得分越高越好。

另外你训练了多少轮

**Comment by bird7code** [comment]
感谢回复！
我在annotation和audio里面都分别加入新数据了，使用的是贪心算法，有什么办法是可以检查自己的数据是否成功加入到训练数据列表的，我的数据都只是放在train里面，test和dev里没放。训练轮数epoch是65

**Comment by yeyupiaoling** [comment]
在train里面就对了。

这样的话，估计是你的数据集和AIShell分布比较大，比较难拟合。或者增加更多的数据和训练轮数

**Comment by bird7code** [comment]
好的，十分感谢。我去尝试一下
