### ISSUE TITLE
predict.py中import paddle应该注释掉，否则会报错

### ISSUE THREAD

**Issue by leishenzhupi** [yeyupiaoling/MASR#35]

**Comment by yeyupiaoling** [comment]
可以安装这个库，因为在标点符号的时候需要用到，当然如果不需要标点符号，可以删掉

**Comment by leishenzhupi** [comment]
好的，我在pytorch框架中安装了paddle框架。我想请问一下我下载了你的一个1000小时的大数据集，我想问一下这个数据集是不公开的，还是由其他一些开源数据及整合其起来的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyupiaoling/MASR] predict.py中import paddle应该注释掉，否则会报错 (Issue #35)





 
可以安装这个库，因为在标点符号的时候需要用到，当然如果不需要标点符号，可以删掉
