### ISSUE TITLE
直接录制语音和上传语音文件，识别效果的差异

### ISSUE THREAD

**Issue by bird7code** [yeyupiaoling/MASR#36]
你好，在Web部署模型中，使用相同的话语，直接录制语音的识别效果和上传语音文件的识别效果差异比较大（上传语音文件的更好），想学习一下这是什么原因

**Comment by yeyupiaoling** [comment]
直接录制语音的识别效果会差吗？

**Comment by bird7code** [comment]
> 直接录制语音的识别效果会差吗？
基本都识别不出来的那种，和录音设备有关吗

**Comment by yeyupiaoling** [comment]
你听听直接录音的音频播放是怎样的

**Comment by bird7code** [comment]
> 你听听直接录音的音频播放是怎样的
听了一下，语音中的字是对的，但是语速很慢，不是原声。只有一点字才识别出来

**Comment by yeyupiaoling** [comment]
那可能是录音有问题

**Comment by bird7code** [comment]
> 那可能是录音有问题
好的谢谢，我检查一下这方面问题
