### ISSUE TITLE
效果好像很差？

### ISSUE THREAD

**Issue by hroken** [yeyupiaoling/MASR#39]
用了第一和第三个模型，直接用的是dataset里面的长语音，识别结果如下：

_最终结果，消耗时间：13005, 得分: 60, 识别结果: ，做品名好，把尺力女争上个有的于树，瑞一直的案与值的知，他着干了，衡厂只丈爸到现止质与人工式，人
指与处，法宽大了一子也是智聘相上几乎没有时生目的，更不勇说赵处婴，她着指光华而游银色的运圈，微微反出战惊子，是是是在被方的风雪的压迫下却保持家
称，这就是白养术希被吉主通的一主，而截不是平法的，法没有普苏的自势没有有需七盘选的职之，别始不养说他不买力，如观美只专职婆说或很十举出折而言，
于止八，拿实是故中的美正，上里在积极出炉了高原上住果，罕景苹厂的罢地上扼然智率这么以朱国应传榜养术，玩照你处只之的数只是数，难到你就不想不的他
澳属由间奖部之就下着而央施医样澳然景力的首位他们家限的照兵，完岛李诱著原一点想到近养之之运人人好紧团结绿球上不尽的怀样术我然想认玩今天转环给职_

是哪里不对吗？

**Comment by yeyupiaoling** [comment]
你用什么解码器？有木有替换项目原来的文件。全文件都复制进来。
