### ISSUE TITLE
数据集标注信息

### ISSUE THREAD

**Issue by leishenzhupi** [yeyupiaoling/MASR#41]
您好，我想问一下，如果标注信息中含有英文字母是不是最后识别不出来？因为我看您在数据准备中说明，标注信息中不能含有英文字母、阿拉伯数字等

**Comment by yeyupiaoling** [comment]
按照模型设计，应该是支持的，但是在集束搜索解码没有对应的语言模型，也没有对应的数据集。所以就做了限制。

**Comment by leishenzhupi** [comment]
好的，感谢！
