### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by qzhsdu** [yeyupiaoling/MASR#47]
作者您好，请问可否分享一下 " 超大数据集(1600多小时真实数据)+(1300多小时合成数据)"

**Comment by qzhsdu** [comment]
作者您好，请问可否分享一下 " 超大数据集(1600多小时真实数据)+(1300多小时合成数据)"

**Comment by yeyupiaoling** [comment]
抱歉，不可以，你自行网上收集和合成
