### ISSUE TITLE
请问模型重训练的相关配置

### ISSUE THREAD

**Issue by 17702513221** [yeyupiaoling/MASR#5]
飘零大佬，我在https://github.com/nl8590687/ASRT_SpeechRecognition提供的开源数据集将近100G，再加上自己贴合项目录制的数据集，总共大概120G，请问可以将你的模型作为权重再训练吗restore_model这里对吗，学习率需要改吗

**Comment by yeyupiaoling** [comment]
@17702513221 你最好重新训练 吧，不同的数据集，你生成的字典都不一样的。

**Comment by yeyupiaoling** [comment]
如果没有问题我就关闭issue了
