### ISSUE TITLE
数据准备部分怎么生成数据列表文件，存在dataset/annotation/目录下

### ISSUE THREAD

**Issue by jiangduwang** [yeyupiaoling/MASR#53]
python create_data.py时报错

**Comment by yeyupiaoling** [comment]
这个要根据自己的数据及实际情况来生成。这部分需要开发者自己完成。

**Comment by jiangduwang** [comment]
好的，谢谢您的即使回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 晚上6:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yeyupiaoling/MASR] 数据准备部分怎么生成数据列表文件，存在dataset/annotation/目录下 (Issue #53)





 这个要根据自己的数据及实际情况来生成。这部分需要开发者自己完成。
