### ISSUE TITLE
运行tune.py报错，提示没有mean_std.npz文件

### ISSUE THREAD

**Issue by jiangduwang** [yeyupiaoling/MASR#54]
我在第一次跑这个项目时，只用了一个数据集，当时觉得效果不好，于是后续三个数据集都使用了，一切过程都很顺利，模型训练好的下一步骤运行tune.py，提示没有mean_std.npz文件；然后我回到数据准备阶段，上面说create_data.py会生成mean_std.npz文件，然而我只生成了mean_std.json文件；config_zh.yml文件里面也是只有mean_std.json，那么请问这个npz文件是在哪个代码文件生成或者是配置文件里面说明的？

**Comment by yeyupiaoling** [comment]
这个tune.py程序是旧的了，暂时用不了。这一步可以忽略掉

**Comment by jiangduwang** [comment]
好的，感谢您的及时答复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yeyupiaoling/MASR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月20日(星期四) 下午3:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yeyupiaoling/MASR] 运行tune.py报错，提示没有mean_std.npz文件 (Issue #54)





 
这个tune.py程序是旧的了，暂时用不了。这一步可以忽略掉
