### ISSUE TITLE
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

### ISSUE THREAD

**Issue by eeric** [yeyupiaoling/MASR#57]

**Comment by eeric** [comment]
原因是：AIShell 里面4个模型用到的torch版本，与自己的不一致

**Comment by yeyupiaoling** [comment]
请导出模型使用。

**Comment by eeric** [comment]
以下2个模型可以导出
MASR_V2-conformer_streaming-fbank-AIShell
MASR_V2-deepspeech2_streaming-fbank-AIShell
遗憾的是：
MASR_V2-efficient_conformer_streaming-fbank-AIShell
MASR_V2-squeezeformer_streaming-fbank-AIShell
导出时报错，是模型定义不一致

**Comment by yeyupiaoling** [comment]
提问题要把错误信息粘出来。

我的猜测应该是你没把配置文件复制进去。
