### ISSUE TITLE
AIShell (179小时) 的预训练模型，是哪个版本torch训练的

### ISSUE THREAD

**Issue by eeric** [yeyupiaoling/MASR#58]
我的版本2个版本：
torch-1.12.1+cu113 torchvision-0.13.1+cu113
torch-1.12.1+cu116 torchvision-0.13.1+cu116
都出错：RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

**Comment by yeyupiaoling** [comment]
你用的是训练模型参数，应该要导出模型才能用的。

**Comment by eeric** [comment]
以下2个模型可以导出
MASR_V2-conformer_streaming-fbank-AIShell
MASR_V2-deepspeech2_streaming-fbank-AIShell
遗憾的是：
MASR_V2-efficient_conformer_streaming-fbank-AIShell
MASR_V2-squeezeformer_streaming-fbank-AIShell
导出时报错，是模型定义不一致

**Comment by yeyupiaoling** [comment]
#57
