### ISSUE TITLE
加入自己数据，训练时候经常出现梯度爆炸

### ISSUE THREAD

**Issue by shenyingying** [yeyupiaoling/MASR#6]
飘零大佬，不知道你用这个网络训练自己的数据集没，我在训练的过程中经常出现梯度爆炸现象，用开源数据集也会出现梯度爆炸！

**Comment by yeyupiaoling** [comment]
@shenyingying 不用担心，训练 练着练着就好了

**Comment by shenyingying** [comment]
> @shenyingying 不用担心，训练 练着练着就好了

但是有时候会自己崩溃，你也会出现nan吗？

**Comment by yeyupiaoling** [comment]
@shenyingying 如果是出现nan就不对了，出现inf还可以自动恢复。
你有没有修改过参数，例如batch size

**Comment by shenyingying** [comment]
> @shenyingying 如果是出现nan就不对了，出现inf还可以自动恢复。
> 你有没有修改过参数，例如batch size

我的batch_size 设置的比较大 128/256

**Comment by yeyupiaoling** [comment]
@shenyingying 学习率呢？有没有调，可以适当减小 学习率。另外要看看你的数据集有没有错误

**Comment by yeyupiaoling** [comment]
没有问题我就关闭issue了
