### ISSUE TITLE
RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True. You can pass `enforce_sorted=False` to pack_padded_sequence and/or pack_sequence to sidestep this requirement if you do not need ONNX exportability

### ISSUE THREAD

**Issue by TszSimLaw** [yeyupiaoling/MASR#64]
MASR-develop/masr/model_utils/deepspeech2/encoder.py", line 41, in forward

x = nn.utils.rnn.pack_padded_sequence(x, x_lens.cpu(), batch_first=True)

in pack_padded_sequence   
 _VF._pack_padded_sequence(input, lengths, batch_first)

RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True. You can pass `enforce_sorted=False` to pack_padded_sequence and/or pack_sequence to sidestep this requirement if you do not need ONNX exportability

**Comment by yeyupiaoling** [comment]
你的pytorch版本是多少，你直接参考我使用的版本

**Comment by Lost-Sunset** [comment]
No module named 'utility'，想问一下作者这个怎么解决

**Comment by yeyupiaoling** [comment]
@Lost-Sunset 你没有全部克隆我的代码吧，源码里面有的
