### ISSUE TITLE
梯度爆炸

### ISSUE THREAD

**Issue by shenyingying** [yeyupiaoling/MASR#7]
飘零大佬，不知道你用这个网络训练自己的数据集没，我在训练的过程中经常出现梯度爆炸现象，用开源数据集也会出现梯度爆炸！

**Comment by yeyupiaoling** [comment]
@shenyingying 不用担心，训练 练着练着就好了

**Comment by yeyupiaoling** [comment]
放在这个issue跟踪问题 #6
