### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by iakRulan** [yeyupiaoling/MASR#71]
作者你好，我用4090单卡训练aishell数据时，200轮大概需要一个月，这是正常的吗

**Comment by yeyupiaoling** [comment]
不正常。你看是不是已经使用了gpu训练？或者是你使用的是Windows系统。

**Comment by iakRulan** [comment]
我是使用的GPU，我是在windows使用WSL2跑的，现在60轮需要11小时左右，

**Comment by yeyupiaoling** [comment]
好的
