### ISSUE TITLE
Aishell-1测试集问题

### ISSUE THREAD

**Issue by CSLJingyu** [yeyupiaoling/MASR#73]
您好，我这边发现用Conformer进行跑Aishell-1的测试集，发现Aishell-1的测试集的实际标签有问题，请问这个实际标签有问题是要自己手动解决嘛？希望您能回答一下我的疑惑，谢谢前辈！

**Comment by yeyupiaoling** [comment]
你说的有问题是指什么呢？音频内容和文本不对吗？

**Comment by CSLJingyu** [comment]
![标签问题](https://github.com/yeyupiaoling/MASR/assets/54651338/b77b551e-56ca-4525-97e8-3cb6d3688d1b)
这是找到的一条
