### ISSUE TITLE
windows系统多卡训练失败

### ISSUE THREAD

**Issue by yjyz1011** [yeyupiaoling/MASR#76]
windows下无法双卡训练，显示nccl不支持。
修改masr/trainer.py，修改backen为gloo后可以支持多卡训练，但是跑完1个eopch后，loss出现异常，显示loss=nan。
求修改。
![Uploading 8888F03CE5C9C5A87CCA97F2F8507B7D.png…]()

**Comment by yjyz1011** [comment]
![Uploading 8888F03CE5C9C5A87CCA97F2F8507B7D.png…]()

**Comment by yeyupiaoling** [comment]
你是在群里提问的那位同学吧。你还是用Ubuntu系统训练吧，
