### ISSUE TITLE
语音文件是如何输入进网络的

### ISSUE THREAD

**Issue by lywhz** [yeyupiaoling/MASR#8]
请问：语音文件不应该先提取特征再输入进cnn网络吗？为什么我没有找到相关特征提取的代码？请大佬指正

**Comment by yeyupiaoling** [comment]
@lywhz 首先是把语音转换成短时傅立叶变换，可以看这段代码：
https://github.com/yeyupiaoling/MASR/blob/dabbd84e8e828ca7f34ef79c81d7489fe3f706a5/utils/data.py#L27-L37

**Comment by yeyupiaoling** [comment]
没有疑问我就关闭issue了
