### ISSUE TITLE
有没有比较可用的语音识别模型

### ISSUE THREAD

**Issue by shenyingying** [yeyupiaoling/MASR#9]
如题

**Comment by yeyupiaoling** [comment]
@shenyingying  文档最后

**Comment by shenyingying** [comment]
> @shenyingying 文档最后

不好意思，我可能没有表述明白自己的意思，我是说的除了这个网络，还有没有其他别的语音识别这块的开源工程，因为我只搜到masr和百度的deepspeech？

**Comment by yeyupiaoling** [comment]
@shenyingying 我目前也只是用着两个模型，其中MASR只能用于学习，如果要应用，最好用DeepSpeech：[https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech](https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech)

**Comment by shenyingying** [comment]
> @shenyingying 我目前也只是用着两个模型，其中MASR只能用于学习，如果要应用，最好用DeepSpeech：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech

但我尝试deepSpeech 好像效果不怎么好，没有masr 效果好

**Comment by yeyupiaoling** [comment]
@shenyingying 你用我的模型咯：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech
同时我也提供了预训练模型，你试一下，但我只训练了十几轮，你先用着试试

**Comment by shenyingying** [comment]
> @shenyingying 你用我的模型咯：https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech
> 同时我也提供了预训练模型，你试一下，但我只训练了十几轮，你先用着试试

MRSR 中单独用自己数据 出了三天nan也没关系吗？

**Comment by yeyupiaoling** [comment]
@shenyingying 出现nan不行的，我说的是出inf还可以回来。看这个回答：https://github.com/yeyupiaoling/MASR/issues/6#issuecomment-706454651

**Comment by yeyupiaoling** [comment]
@shenyingying 还有疑问吗？没有我就关闭issue了
